---
- name: Setup Web Server with Git, MongoDB, Docker, and Gemini API
  hosts: all
  become: true
  tasks:

    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Clone MemeGenerator repository
      git:
        repo: 'https://github.com/roee4647/MemeGenerator'
        dest: /home/ec2-user/App/MemeGenerator
        update: yes



    - name: Add MongoDB repo
      copy:
        dest: /etc/yum.repos.d/mongodb-org-8.0.repo
        content: |
          [mongodb-org-8.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/8.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://pgp.mongodb.com/server-8.0.asc

    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: present

    - name: Update MongoDB bindIp to 0.0.0.0
      lineinfile:
        path: /etc/mongod.conf  # Adjust the path if it's different on your system
        regexp: '^(\s*bindIp:).*'
        line: '  bindIp: 0.0.0.0'  # Ensure proper indentation here
      tags:
        - bind_all_ip
       
      
    - name: Start MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Build Docker image for MemeMongoApp using shell
      shell: "docker build -t meme-mongo-app /home/ec2-user/App/MemeGenerator/MongoDbMemes"
      args:
        chdir: /home/ec2-user/App/MemeGenerator/MongoDbMemes  # Ensure it's in the correct directory
      tags:
        - build_container


    - name: Run MemeMongoApp container
      docker_container:
        name: meme-mongo-app
        image: meme-mongo-app:latest  # Use the image built in the previous step
        state: started
        restart_policy: always
        published_ports:
          - "80:5001"
        env:
          GEMINI_API_KEY: "{{ lookup('env', 'GEMINI_API_KEY') }}"
          EC2_PUBLIC_IP: "{{ lookup('env', 'EC2_PUBLIC_IP') }}"
      tags:
        - run_container
